name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: dependencies
      run: |
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get install -y php7.4-dev
        sudo apt remove -y php8.1 php8.1-dev
        sudo update-alternatives --list php
        sudo update-alternatives --set php /usr/bin/php7.4
        sudo update-alternatives --list php
    - name: php version
      run: php --version
    - uses: actions/checkout@v3
    - name: phpize
      run: phpize7.4
    - name: configure
      run: ./configure --enable-bfr
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
